### ISSUE TITLE
Getting kicked when using .enchant command

### ISSUE THREAD

**Issue by mcbartek22** [optipack/asteroid#1]
### Describe the bug

when trying to use enchant command i get kicked from server and get this exception:
Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'serverbound/minecraft:set_creative_mode_slot'

### Steps to reproduce

1. Be in creative (singleplayer/multiplayer)
2. Grab Netherite sword or any enchatable item
3. run .enchant one minecraft:unbreaking level 3

### Meteor Version

Asteroid 0.2.2

### Minecraft Version

1.21.1 (Fabric 0.16.9)

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by moxvallix** [comment]
Fixed in latest version
